-- Insert sample leave types data
-- Run this in Supabase SQL Editor to add sample data

INSERT INTO leave_types (
    name,
    code,
    description,
    color,
    is_paid,
    requires_approval,
    requires_medical_certificate,
    min_advance_notice_days,
    has_annual_quota,
    default_quota_days,
    quota_calculation_method,
    allow_carry_forward,
    max_carry_forward_days,
    carry_forward_expiry_months,
    is_prorated,
    is_active
) VALUES 
(
    'Annual Leave',
    'AL',
    'Yearly vacation entitlement for rest and recreation',
    '#3B82F6',
    true,
    true,
    false,
    7,
    true,
    21.0,
    'yearly',
    true,
    7.0,
    3,
    true,
    true
),
(
    'Sick Leave',
    'SL',
    'Medical leave for illness or medical appointments',
    '#EF4444',
    true,
    false,
    true,
    0,
    true,
    14.0,
    'yearly',
    false,
    null,
    null,
    true,
    true
),
(
    'Emergency Leave',
    'EL',
    'Urgent personal or family emergency situations',
    '#F59E0B',
    true,
    true,
    false,
    0,
    true,
    5.0,
    'yearly',
    false,
    null,
    null,
    true,
    true
),
(
    'Maternity Leave',
    'ML',
    'Leave for new mothers before and after childbirth',
    '#8B5CF6',
    true,
    true,
    true,
    30,
    true,
    90.0,
    'yearly',
    false,
    null,
    null,
    false,
    true
),
(
    'Study Leave',
    'STL',
    'Educational leave for training or professional development',
    '#10B981',
    true,
    true,
    false,
    14,
    true,
    10.0,
    'yearly',
    true,
    5.0,
    3,
    true,
    true
);

-- Check if data was inserted
SELECT * FROM leave_types ORDER BY name;
